name: Build Image Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t moteapp.azurecr.io/mote:latest
        docker push moteapp.azurecr.io/mote:latest
    
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'moteapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'moteapp.azurecr.io/myapp:${{ github.sha }}'